"""users sessions polygon owner

Revision ID: 38872658c928
Revises: f75adb043099
Create Date: 2026-09-05 13:29:04.728397
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# geoalchemy2 обязателен в каждой миграции, где встречается Geometry: autogenerate
# подставляет `geoalchemy2.types.Geometry(...)` в определение колонки, но импорт
# сам не добавляет, и миграция падает с NameError уже при upgrade.
import geoalchemy2


revision: str = '38872658c928'
down_revision: str | None = 'f75adb043099'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('braining_user_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('braining_user_id')
    )
    op.create_index('ix_users_braining_id', 'users', ['braining_user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_sessions_token', 'sessions', ['token_hash'], unique=False)
    op.create_index('ix_sessions_user', 'sessions', ['user_id'], unique=False)
    op.add_column('polygons', sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_index('ix_polygons_user', 'polygons', ['user_id'], unique=False)
    op.create_foreign_key(None, 'polygons', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'polygons', type_='foreignkey')
    op.drop_index('ix_polygons_user', table_name='polygons')
    op.drop_column('polygons', 'user_id')
    op.drop_index('ix_sessions_user', table_name='sessions')
    op.drop_index('ix_sessions_token', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_users_braining_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
