"""polygon source_id properties validation_notes updated_at

Revision ID: 8d72a4b3a1a7
Revises: 9f99468df5c4
Create Date: 2026-09-05 09:09:23.072071
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# geoalchemy2 обязателен в каждой миграции, где встречается Geometry: autogenerate
# подставляет `geoalchemy2.types.Geometry(...)` в определение колонки, но импорт
# сам не добавляет, и миграция падает с NameError уже при upgrade.
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = '8d72a4b3a1a7'
down_revision: str | None = '9f99468df5c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polygons', sa.Column('source_id', sa.String(length=200), nullable=True))
    op.add_column('polygons', sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('polygons', sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('polygons', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polygons', 'updated_at')
    op.drop_column('polygons', 'validation_notes')
    op.drop_column('polygons', 'properties')
    op.drop_column('polygons', 'source_id')
    # ### end Alembic commands ###
