"""reconstruction climatology

Revision ID: f75adb043099
Revises: 8d72a4b3a1a7
Create Date: 2026-09-05 10:33:03.516172
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# geoalchemy2 обязателен в каждой миграции, где встречается Geometry: autogenerate
# подставляет `geoalchemy2.types.Geometry(...)` в определение колонки, но импорт
# сам не добавляет, и миграция падает с NameError уже при upgrade.
import geoalchemy2


revision: str = 'f75adb043099'
down_revision: str | None = '8d72a4b3a1a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reconstructions', sa.Column('climatology_mean', sa.Float(), nullable=True))
    op.add_column('reconstructions', sa.Column('climatology_std', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reconstructions', 'climatology_std')
    op.drop_column('reconstructions', 'climatology_mean')
    # ### end Alembic commands ###
